var stubENTRY1 = [ 'Primary Name',
  'Splendor',
  'Alternate Names',
  'เกมค้าเพชร',
  '宝石の煌き',
  '璀璨寶石',
  '스플렌더',
  'Year Published',
  '2014',
  'Designer',
  'Marc André',
  'Artist',
  'Pascal Quidault',
  'Publishers',
  'Space Cowboys',
  'Asmodee',
  'Asterion Press',
  'Broadway Toys LTD',
  'Filosofia Éditions',
  'Galápagos Jogos',
  'Gém Klub Kft.',
  'GoKids 玩樂小子',
  'Hobby Japan',
  'Kaissa Chess & Games',
  'Korea Boardgames co.',
  ' Ltd.',
  'Lautapelit.fi',
  'REBEL.pl',
  'Siam Board Games',
  'Categories',
  'Card Game',
  'Economic',
  'Renaissance',
  'Mechanisms',
  'Card Drafting',
  'Set Collection',
  'Family',
  'Splendor' ],

  stubENTRY2 = [ 'Primary Name',
  'Forbidden Island',
  'Alternate Names',
  'Den Forbudte Øya',
  'A Ilha Proibida',
  'La Isla Prohibida',
  'L\'Île Interdite',
  'L\'illa prohibida',
  'L\'Isola Proibita',
  'Salaisuuksien saari',
  'Het Verboden Eiland',
  'Die verbotene Insel',
  'Zakazana Wyspa',
  'Zakázaný ostrov',
  'Η απαγορευμένη νήσος',
  'Запретный остров',
  'האי הנעלם',
  '禁制之島',
  'Year Published',
  '2010',
  'Designer',
  'Matt Leacock',
  'Artist',
  'C. B. Canga',
  'Publishers',
  'ADC Blackfire Entertainment',
  'Cocktail Games',
  'Competo / Marektoy',
  'Devir',
  'FoxMind Israel',
  'Gamewright',
  'Kaissa Chess & Games',
  'Kanga Games',
  'Lifestyle Boardgames Ltd',
  'REBEL.pl',
  'Schmidt Spiele',
  'uplay.it edizioni',
  'White Goblin Games',
  'Categories',
  'Adventure',
  'Card Game',
  'Fantasy',
  'Mechanisms',
  'Action Point Allowance System',
  'Co-operative Play',
  'Grid Movement',
  'Hand Management',
  'Modular Board',
  'Pick-up and Deliver',
  'Set Collection',
  'Variable Player Powers',
  'Family',
  'Forbidden Games',
  'Mensa Select' ]

  module.exports = {stubENTRY1, stubENTRY2};
