var stubDATA1 = [ 'Primary Name',
  'Pandemic Legacy: Season 1',
  'Alternate Names',
  'Pandemic Legacy: Saison 1',
  'Pandemic Legacy: 1. Évad',
  'Pandemic Legacy: Rok 1',
  'Pandemic Legacy: Rok 1',
  'Pandemic Legacy: Seizoen 1',
  'Пандемия: Наследие',
  'パンデミックレガシー シーズン1',
  '瘟疫危機︰承傳',
  'Year Published',
  '2015',
  'Designer',
  'Rob Daviau',
  'Matt Leacock',
  'Artist',
  'Chris Quilliams',
  'Publishers',
  'Z-Man Games',
  'Asterion Press',
  'Devir',
  'Filosofia Éditions',
  'Gém Klub Kft.',
  'Hobby Japan',
  'Jolly Thinkers',
  'Lacerta',
  'Lifestyle Boardgames Ltd',
  'MINDOK',
  'Categories',
  'Environmental',
  'Medical',
  'Mechanisms',
  'Action Point Allowance System',
  'Co-operative Play',
  'Hand Management',
  'Point to Point Movement',
  'Set Collection',
  'Trading',
  'Variable Player Powers',
  'Family',
  'Campaign Games',
  'Legacy',
  'Pandemic' ],

  stubDATA2 = [ 'Primary Name',
  'Through the Ages: A New Story of Civilization',
  'Alternate Names',
  'Cywilizacja: Poprzez Wieki',
  'Im Wandel der Zeitalter: Ein neue Geschichte der Zivilisation',
  'Korokon át: A civilizáció új története',
  'Korokon át: A civilizáció új története',
  'Through the Ages',
  'Through the Ages: Eine neue Geschichte der Zivilisation',
  'Through the Ages: L\'Histoire vous appartient',
  'Through the Ages: Nový příběh civilizace',
  'Through the Ages: Nový příběh civilizace',
  'Through the Ages: Rivivi la Storia della Civiltà',
  'Through the Ages: Uma Nova História da Civilização',
  'Through the Ages: Una Nueva Historia de la Civilización',
  '历史巨轮：人类文明新篇章',
  '쓰루 디 에이지스: 새로운 인류 문명 발전 대서사시',
  'Year Published',
  '2015',
  'Designer',
  'Vlaada Chvátil',
  'Artists',
  'Jakub Politzer',
  'Milan Vavroň',
  'Publishers',
  'Cranio Creations',
  'Czech Games Edition',
  'Devir',
  'DiceTree Games',
  'Eagle-Gryphon Games',
  'Gém Klub Kft.',
  'Heidelberger Spieleverlag',
  'IELLO',
  'MINDOK',
  'One Moment Games',
  'REBEL.pl',
  'Categories',
  'Card Game',
  'Civilization',
  'Economic',
  'Mechanisms',
  'Action Point Allowance System',
  'Auction/Bidding',
  'Card Drafting',
  'Hand Management',
  'Family',
  'Tableau Building' ],

  stubDATA3 = [ 'Primary Name',
  'Pandemic',
  'Alternate Names',
  'EPIZOotic',
  'Pandemia',
  'Pandemia: Una Nuova Sfida',
  'Pandémie',
  'Pandemie',
  'Πανδημία',
  'Пандемия',
  'パンデミック',
  'パンデミック：新たなる試練',
  '瘟疫危機 (瘟疫危机)',
  '팬데믹',
  'Year Published',
  '2008',
  'Designer',
  'Matt Leacock',
  'Artists',
  'Josh Cappel',
  'Christian Hanisch',
  'Régis Moulun',
  'Chris Quilliams',
  'Tom Thiel',
  'Publishers',
  'Z-Man Games',
  '(Unknown)',
  'Albi',
  'Asterion Press',
  'Brain Games',
  'Devir',
  'Filosofia Éditions',
  'Gém Klub Kft.',
  'Hobby Japan',
  'HomoLudicus',
  'Jolly Thinkers',
  'Kaissa Chess & Games',
  'Korea Boardgames co.',
  ' Ltd.',
  'Lacerta',
  'Lautapelit.fi',
  'Lifestyle Boardgames Ltd',
  'MINDOK',
  'Nordic Games GmbH',
  'Paladium Games',
  'Pegasus Spiele',
  'Quined White Goblin Games',
  'Stratelibri',
  'Wargames Club Publishing',
  'White Goblin Games',
  'Взрослые дети',
  'Category',
  'Medical',
  'Mechanisms',
  'Action Point Allowance System',
  'Co-operative Play',
  'Hand Management',
  'Point to Point Movement',
  'Set Collection',
  'Variable Player Powers',
  'Family',
  'Pandemic' ],

  stubDATA4 = [ 'Primary Name',
  'Twilight Struggle',
  'Alternate Names',
  'Gleichgewicht des Schreckens',
  'Studená válka 1945-1989',
  'Zimna wojna 1945-1989',
  'トワイライト・ストラグル',
  '冷战热斗 (冷戰熱鬥)',
  '晨昏对峙（晨昏對峙）',
  '황혼의 투쟁',
  'Year Published',
  '2005',
  'Designers',
  'Ananda Gupta',
  'Jason Matthews',
  'Artists',
  'Viktor Csete',
  'Rodger B. MacGowan',
  'Chechu Nieto',
  'Guillaume Ries',
  'Mark Simonitch',
  'Publishers',
  'GMT Games',
  '(Self-Published)',
  'Asterion Press',
  'Bard Centrum Gier',
  'Chrononauts Games',
  'Devir',
  'DiceTree Games',
  'MINDOK',
  'Udo Grebe Gamedesign',
  'Wargames Club Publishing',
  'Categories',
  'Modern Warfare',
  'Political',
  'Wargame',
  'Mechanisms',
  'Area Control / Area Influence',
  'Campaign / Battle Card Driven',
  'Dice Rolling',
  'Hand Management',
  'Simultaneous Action Selection',
  'Family',
  'Country: Russia',
  'Country: USA' ],

  stubDATA5 = [ 'Primary Name',
  'Terra Mystica',
  'Alternate Names',
  'Терра Мистика',
  'テラミスティカ',
  '神秘大地',
  '테라 미스티카',
  'Year Published',
  '2012',
  'Designers',
  'Jens Drögemüller',
  'Helge Ostertag',
  'Artist',
  'Dennis Lohausen',
  'Publishers',
  'Feuerland Spiele',
  'Bard Centrum Gier',
  'Cranio Creations',
  'Devir',
  'Filosofia Éditions',
  'FunBox Jogos',
  'HomoLudicus',
  'MINDOK',
  'Swan Panasia Co.',
  ' Ltd.',
  'テンデイズゲームズ (Ten Days Games)',
  'White Goblin Games',
  'Z-Man Games',
  'Zvezda',
  'Categories',
  'Civilization',
  'Economic',
  'Fantasy',
  'Territory Building',
  'Mechanisms',
  'Route/Network Building',
  'Variable Phase Order',
  'Variable Player Powers',
  'Family',
  'Terra Mystica' ]

  module.exports = {stubDATA1, stubDATA2, stubDATA3, stubDATA4, stubDATA5}
